services:
  - type: web
    name: investpal-backend
    runtime: node
    repo: https://github.com/Investxp/investpal--bot-backend
    branch: master
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: DERIV_APP_ID
        sync: false
      - key: DERIV_TOKEN
        sync: false
      - key: POLYMARKET_API_KEY
        sync: false
      - key: POLYMARKET_API_SECRET
        sync: false
      - key: POLYMARKET_PASSPHRASE
        sync: false
      - key: POLYMARKET_PRIVATE_KEY
        sync: false
      - key: SX_PRIVATE_KEY
        sync: false
      - key: SX_WALLET_ADDRESS
        sync: false
      - key: NODE_VERSION
        value: 22
